#!/bin/bash
#Launches multiple parties for distributed computation

[ -e _cloud ] && rm -r _cloud

n=10
for i in `seq 0 $((n-1))`; do
  xfce4-terminal -H --geometry=90x16+$(($RANDOM % 1200))+$(($RANDOM % 800)) --command "./party.py $i"
done
