#!/bin/bash
#Runs a distributor and multiple parties

[ -e _cloud ] && rm -r _cloud

i=0
n=10
while [[ $i -lt $n ]]; do
  xfce4-terminal -H --geometry=90x16+$(($RANDOM % 1200))+$(($RANDOM % 800)) --command "./party.py $i"
  i=$((i+1))
done
